// <auto-generated />
namespace BHI_Asset_Portal_WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewIDs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewIDs));
        
        string IMigrationMetadata.Id
        {
            get { return "201909231938551_NewIDs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
