// <auto-generated />
namespace BHI_Asset_Portal_WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class move : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(move));
        
        string IMigrationMetadata.Id
        {
            get { return "201909221614048_move"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
